language: scala

scala:
- 2.11.8

jdk:
- oraclejdk8

script: ./scripts/build.sh

notifications:
  email: false

cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2

before_cache:
  - du -h -d 1 $HOME/.ivy2
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
